{% set version = "5.15.11" %}
{% set sip_version = "6.10.0" %}

package:
  name: pyqtwebkit
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}/PyQt{{ version[0] }}-{{ version }}.tar.gz
    sha256: fda45743ebb4a27b4b1a51c6d8ef455c4c1b5d610c90d2934c7802b5c1557c52
    folder: pyqt
    patches:
      - remove-deleted-xkb-keys.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - jom                                    # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pyqt-builder                           # [build_platform != target_platform]
    - sip {{ sip_version }}                  # [build_platform != target_platform]
    - make
  host:
    - python
    - setuptools
    - pip
    - sip {{ sip_version }}                  # [build_platform == target_platform]
    - toml
    - pyqt-builder                           # [build_platform == target_platform]
    - packaging
    - qt-main
    - qtwebkit
    - pyqt
    - libgl-devel                            # [linux]
    - libegl-devel                           # [linux]
    - libopengl-devel                        # [linux]
    - xorg-xorgproto                         # [linux]
    - xcb-util                               # [linux]
    - xcb-util-wm                            # [linux]
    - xcb-util-keysyms                       # [linux]
    - xcb-util-image                         # [linux]
    - xcb-util-renderutil                    # [linux]
    - xorg-libx11                            # [linux]
    - xorg-libxext                           # [linux]
    - xorg-libxdamage                        # [linux]
    - xorg-libsm                             # [linux]
    - xorg-libice                            # [linux]
    - xorg-libxcomposite                     # [linux]
    - xorg-libxxf86vm                        # [linux]
    - xorg-xf86vidmodeproto                  # [linux]
  run:
    - python
    - pyqt
    - qtwebkit
test:
  files:
    - pyqt_test.py
  imports:
    - PyQt5.QtWebKit
    - PyQt5.QtWebKitWidgets
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux and build_platform == target_platform]
    - python pyqt_test.py  # [not linux and build_platform == target_platform]

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: LicenseRef-Commercial or GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python binding of the cross-platform GUI toolkit Qt. QtWebKit only.
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/

extra:
  recipe-maintainers:
    - gillins
    - ocefpaf
    - dakcarto
    - SrNetoChan
