{% set version = "5.15.7" %}

package:
  name: pyqtwebkit
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/P/PyQt{{ version[0] }}/PyQt{{ version[0] }}-{{ version }}.tar.gz
    sha256: 755121a52b3a08cb07275c10ebb96576d36e320e572591db16cfdbc558101594
    folder: pyqt


build:
  number: 3
  skip: true  # [not x86_64]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - jom                                # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pyqt-builder                           # [build_platform != target_platform]
    - sip                                    # [build_platform != target_platform]
    - make
  host:
    - python
    - pip
    - sip                                    # [build_platform == target_platform]
    - toml
    - pyqt-builder                           # [build_platform == target_platform]
    - packaging
    - qt-main
    - qtwebkit
    - pyqt
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - {{ cdt('mesa-libegl-devel') }}         # [linux]
  run:
    - python
    - pyqt
    - qtwebkit
test:
  files:
    - pyqt_test.py
  imports:
    - PyQt5.QtWebKit
    - PyQt5.QtWebKitWidgets
  commands:
    # Crashes - not sure why - works on a local xsession. Comment out for now.
    #- DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'  # [linux]
    - python pyqt_test.py  # [not linux]

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: LicenseRef-Commercial or GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python binding of the cross-platform GUI toolkit Qt. QtWebKit only.'
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/

extra:
  recipe-maintainers:
    - gillins
    - ocefpaf
    - dakcarto
    - SrNetoChan
